### ISSUE TITLE
Unable to make assertions on incoming requests to GET routes

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/jamming-nx#4]
I would like my GET routes to reject possible requests that don't match a specific pattern. For example, when a request is made to [this route](https://github.com/mdwiltfong/jamming-nx/blob/bbd60ad2648597f4700e99066cb2009900bc5c20/jamming-app/apps/jamming-api/src/routes/userRouter.ts#L7), I want the server to immediately throw an error before it sends some random string to the DB. 

So with how it's currently setup, if a GET request is made to `/users/cheese` the app will pass the word "cheese" to the DB, and the DB will query for an ID that matches "cheese." Obviously there's no document with an ID of "cheese." The IDs are UUIDs. So they are similar to `91659038-4dfe-4bc4-a997-31f6f1b2598d` .Ideally I should be scrubbing this data before it's sent to the DB. 

I'm currently using `yup` to create a middleware function to validate these URLs. You can find the logic for the middleware [here](https://github.com/mdwiltfong/jamming-nx/blob/bbd60ad2648597f4700e99066cb2009900bc5c20/jamming-app/apps/jamming-api/src/schemas/userSchema.ts#L13-L39) and it's impelmentation [here](https://github.com/mdwiltfong/jamming-nx/blob/bbd60ad2648597f4700e99066cb2009900bc5c20/jamming-app/apps/jamming-api/src/server.ts#L11).

Any help in getting this regex to work would greatly be appreciated! Another possibility is maybe making the UUIDs less random. For example users UUIDs could start with "JUSER" for "Jamming App User." This might make it easier to write more predictable regexs.

**Comment by toreylittlefield** [comment]
@mdwiltfong are you saying you want to validate that the id is a 32 character long uuid separated by dashes?

**Comment by Holiv** [comment]
Maybe you should try the [Validator](https://www.npmjs.com/package/validator ) calling its `isUUID` method. Returning false, you can throw an exception or handle in a way it fits better.
